### ISSUE TITLE
Bug: om-headline-set-node-property returns ':post-blank' error

### ISSUE THREAD

**Issue by floscr** [ndwarshuis/om.el#10]
Trying to set properties with `om-headline-set-node-property` returns the error:

```
om--arg-error: Argument type error: "Type ’node-property’ does not have property ’:post-blank’"
```

Here's the function:

```elisp
(->> (om-parse-this-headline)
         (om-update (lambda (hl)
                      (->> hl
                           (om-headline-set-node-property "FOO" "BAR")))))
```

And it errors on headers with properties as well as headers without.

**Comment by ndwarshuis** [comment]
Please post an example of a headline that fails (and any that don't if there are any).

I just tried this on a few arbitrary headlines and didn't get any errors.

**Comment by floscr** [comment]
I'm very sorry, it was again a reload issue, I'll take a better look next time.
