### ISSUE TITLE
Fix melpa homepage link

### ISSUE THREAD

**Issue by Trevoke** [ndwarshuis/om.el#12]
The homepage link is marked as 
![image](https://user-images.githubusercontent.com/67913/89558763-a4760480-d7e2-11ea-9662-ab3fff272e9f.png)

Which is a broken link, I had to remove the `.el` to come to this page :)

**Comment by ndwarshuis** [comment]
Where are you seeing this? There were a few `org-ml.el`s that I fixed in the last commit but I didn't see one that looked like it was in the context you are showing

**Comment by Trevoke** [comment]
Oh, I was looking at Melpa stable, that's why: https://stable.melpa.org/#/org-ml

**Comment by ndwarshuis** [comment]
rookie mistake, I forgot to push the latest tags :( the current latest is 2.0.1
