### ISSUE TITLE
incompat status in melpa

### ISSUE THREAD

**Issue by iantor** [ndwarshuis/om.el#15]
org-ml             20200902.133  incompat   melpa      Functional Org Mode API

emacs 26.3 on windows 10
org 9.3.7

(setq package-archives '(
			 ("gnu" . "http://elpa.gnu.org/packages/")
			 ("org" . "http://orgmode.org/elpa/")
			 ("melpa" . "http://melpa.org/packages/")))

**Comment by ndwarshuis** [comment]
a8fa7c1648b77e9709fff54e2674d2a7e67e7638 should fix this but you probably need to wait until melpa syncs again to see if the same error happens

**Comment by iantor** [comment]
working now.  I have installed it from melpa.  Previously it was also labelled as an "obsolete" package but I no longer see this.
