### ISSUE TITLE
org-ml-to-string returns title property concatenated 4 times

### ISSUE THREAD

**Issue by hrehfeld** [ndwarshuis/om.el#17]
``` org-mode
* bar foo
# (org-ml-to-string (org-ml-get-property :title (org-ml-parse-this-headline)))

# this evaluates to 1:
# (length (org-ml-get-property :title (org-ml-parse-this-headline)))
```
Just evaluate the call in the comment, it returns the title text concatenated four times. Am I somehow still using this incorrectly?

**Comment by ndwarshuis** [comment]
For this particular case you just need `(org-ml-get-property :raw-value (org-ml-parse-this-headline))` to get the title of a headline as a string. The `:title` property is a secondary string (technically a list of strings and object nodes) and `org-ml-to-string` only knows how to handle single nodes.

If you wanted to convert a secondary string to a string with `org-ml-to-string` you would need something like `(mapconcat #'org-ml-to-string (org-ml-get-property :title (org-ml-parse-this-headline)) "")`. Secondary strings are only used in the `:title` and `:tag` properties for headlines and items respectively, and headlines already have `:raw-value` so I didn't figured it wouldn't be necessary to add another function just to directly stringify secondary strings.

**Comment by hrehfeld** [comment]
Thanks for the clarification!

Wouldn't it be a good idea to have some sort of check there instead of garbage behavior?

**Comment by ndwarshuis** [comment]
That's a good idea, added with d9a75ef2c89fac244ce07f3a6d0bd4a9446b5ebc which should be merged to master in a few weeks or so with a bunch of other stuff.
