### ISSUE TITLE
Should indent/unindent be called promote/demote?

### ISSUE THREAD

**Issue by andersjohansson** [ndwarshuis/om.el#20]
Hi and thanks for org-ml!
I was looking for functions doing what in org is usually called "promoting" and "demoting" (for example `org-promote`) and realized that this is achieved with the indent/unindent functions.

Would it be better to use function names like "demote" and "promote" to better reflect the terminology in org-mode (even though I realize that org-ml intentionally departs from some of the terminology in org-element)? "Indent" is also used for things relating to real or displayed whitespace in org-mode.

**Comment by ndwarshuis** [comment]
Thanks for pointing this out. I take it you mean specifically renaming `org-ml-headline-indent-*` (because it looks like there is a function `org-intent-item` which pertains to items)?

> "Indent" is also used for things relating to real or displayed whitespace in org-mode.

Not sure exactly what you mean by this. Can you point to specific functions where this is the case?

**Comment by andersjohansson** [comment]
You are right, this is another place where org is perhaps a bit inconsistent: The functions for plain lists use “indent” and “outdent” while the functions for headlines use “demote” and “promote”. However plain-list “level” is dictated by indentation with spaces, as opposed to number of stars for headlines, so for that reason “indent”/“outdent” is more appropriate in that case.

Sorry, I was thinking of:
- `org-adapt-indentation` (“When this variable is set to t, Org assumes that you write outlines by indenting text in each node to align with the headline (after the stars).”)
- `org-indent-mode`, which displays content below headlines as indented through display-properties even when all lines in the text are “flush-left”

**Comment by ndwarshuis** [comment]
Ok thanks, that clarifies things.

So for headlines, the renaming would go something like this:
- `org-ml-headline-indent-subheadline` -> `org-ml-headline-promote-subheadline` (same as `org-promote`)
- `org-ml-headline-indent-subtree` -> `org-ml-headline-promote-subtree` (same as `org-promote-subtree`)
- `org-ml-headline-unindent-subheadline` -> `org-ml-headline-demote-subheadline` (same as `org-demote`)
- `org-ml-headline-unindent-subtree` -> `org-ml-headline-demote-subtree` (same as `org-demote-subtree`)

For plain-lists/items, they already seem to follow the same naming scheme (except that org itself doesn't seem to have the unindent analogues unless I'm missing something; the closest thing I could find is `org-cycle-item-indentation`):
- `org-ml-plain-list-indent-item` -> no change (same as `org-indent-item`)
- `org-ml-plain-list-unindent-item` -> no change
- `org-ml-plain-list-indent-item-tree` -> no change (same as `org-indent-item-tree`)
- `org-ml-plain-list-unindent-all-items` -> no change

I just realized that there is no reverse analogue of `org-ml-plain-list-indent-item-tree` so I might convert `org-ml-plain-list-unindent-all-items` to be that just to be consistent.

Besides that, does what I have above make more sense considering what is already in org? I realize the names are a bit longer but I personally think the pattern of `org-ml-THING-ACTION-OBJECT` is more explicit. Also having `plain-list` and `item` in the name of the indenting functions should hopefully clear any confusion between the purpose of these and `org-adapt-indentation` and `org-indent-mode`.

**Comment by andersjohansson** [comment]
Hi, sorry for taking a while. I believe you turned it around in your comment above. "Promote" in org refers to taking a headline higher up in the hierarchy, that is, "lowering" its level and unindenting it to the left (I have actually previously had to think about this for a while when using the function names, it is not obvious and easy to think of promote as increase level/indentation). So it should be:

* `org-ml-headline-indent-subheadline` -> `org-ml-headline-demote-subheadline` (same as `org-demote`)
* `org-ml-headline-indent-subtree` -> `org-ml-headline-demote-subtree` (same as `org-demote-subtree`)
* `org-ml-headline-unindent-subheadline` -> `org-ml-headline-promote-subheadline` (same as `org-promote`)
* `org-ml-headline-unindent-subtree` -> `org-ml-headline-promote-subtree` (same as `org-promote-subtree`)

For the plain list functions. It looks right to keep the names, but there are actually unindent analogues in org, named "outdent": `org-outdent-item` and `org-outdent-item-tree`. I am not sure if that is better, but if you want to follow org perhaps "outdent" should be chosen over "unindent". I’m not a native English speaker (nor a professional programmer) so I’m not sure what word is most commonly used. [Wikipedia says](https://en.wikipedia.org/wiki/Indentation_(typesetting)): “In computer programming, the neologisms outdent, unindent and dedent are used to describe the reversal of the indentation process”.

I like the names otherwise, and the `plain-list` and `item` makes it clear.

**Comment by ndwarshuis** [comment]
That makes sense, thanks for clarifying. I'll keep the 'outdent' language just to stay consistent

**Comment by ndwarshuis** [comment]
fixed with d87efb05c4a6c8dd2d8525c201a73b90b383a85a
