### ISSUE TITLE
Parse a timestamp string (e.g. from a CREATED property)?

### ISSUE THREAD

**Issue by hrehfeld** [ndwarshuis/om.el#21]
Is there an elegant way to parse a timestamp string like `"[2020-10-30 09:25]"`?

Currently I'm doing:

```
(defun my-org-ml-parse-timestamp (str)
	(with-temp-buffer
		(insert str)
		(goto-char (point-min))
		(org-ml-parse-this-object)))
```

**Comment by ndwarshuis** [comment]
Not really, currently there's an internal function called `org-ml--from-string` which will give you the timestamp wrapped in a paragraph and section but that's not elegant and it's an internal function so it may change at any time.

What exactly are you trying to do?

**Comment by hrehfeld** [comment]
OK, thanks for the awesomely fast response! :+1: 

I'm just trying to sort a list of headlines by the CREATED property. Just sorting with `string<` won't cut it, because of active and inactive dates (`[` vs. `<`).
``` emacs-lisp
(defun my-org-clean-get-created (headline) (org-ml-headline-get-node-property "CREATED" headline))

(defun my-org-clean-parse-timestamp (str)
  (with-temp-buffer
    (insert str)
    (goto-char (point-min))
    (org-ml-parse-this-object)))

(defun my-org-clean--sort (headlines)
  (cl-flet* ((clean-timestamp (str)
                              (org-ml-time-to-unixtime
                               (org-ml-timestamp-get-start-time
                                (my-org-clean-parse-timestamp str))))
             (compare (a b)
                     ;; try created
                     (let ((a-prop (my-org-clean-get-created a))
                           (b-prop (my-org-clean-get-created b)))
                       (if (and a-prop b-prop)
                          (< (clean-timestamp a-prop)
                                (clean-timestamp b-prop))
                         ;; I cut some fallback sorting stuff for the paste, so not tested
                         (not b-prop)))))
    (->> headlines
         (-sort #'compare)
         (--map (org-ml-headline-set-subheadlines
                 (my-org-clean--sort (org-ml-headline-get-subheadlines it))
                 it))
         )))

```

**Comment by ndwarshuis** [comment]
Ok got it.

I've thought about adding a more friendly version of `org-ml--from-string` to do exactly what you want but didn't because I thought the use cases would be limited (TBH I can't think of many other cases beside this one where it would be useful). Since someone else thinks this would be useful I can add it in the upcoming version bump ;)

The implementation would be basically what you have in the OP since org-element only operates directly on buffers (eg there's no way around the `with-temp-buffer` thing), so for now that's the workaround.

**Comment by neeasade** [comment]
@hrehfeld you might also take a look at ts.el: https://github.com/alphapapa/ts.el -- it's what i use to parse and compare dates for sorting stuff with org-ml currently. eg https://github.com/alphapapa/ts.el/blob/master/ts.el#L326

**Comment by ndwarshuis** [comment]
@hrehfeld I'm almost done incorporating a new version of `org-ml-from-string` as a generic way of converting strings to nodes, but I also realized (in addition to @neeasade's comment above) you can just use `org-2ft` on a string to get the epoch time for numeric comparison:

```
(org-2ft "[2020-01-01 Tue]")
;; 1577854800.0
```

**Comment by ndwarshuis** [comment]
I added a generic `org-ml-from-string` function in f0513bd5a3d7ad7fd7e4cf752c479bf2d537415a but @neeasade's solution or the `org-2ft` thing I mentioned above might be faster in your case ;)
