### ISSUE TITLE
`org-ml-get-headlines` only returns headlines with level 1 and 2

### ISSUE THREAD

**Issue by maxchaos** [ndwarshuis/om.el#25]
Hi. As the title says, running `org-ml-get-headlines` in the following buffer only returns the headlines "Heading 1" and "Heading 2".
```
* Heading 1
** Heading 2
*** Heading 3
```
Is this supposed to be the expected behaviour?

**Comment by ndwarshuis** [comment]
Nope, this is a regression

It should actually return `("* Heading 1\n** Heading 2\n*** Heading 3" "** Heading 2\n*** Heading 3" "*** Heading 3")` (albeit as nodes not as string representations, the point is the top-level headlines will contain the headlines inside them and then the one's inside will be repeated)

**Comment by maxchaos** [comment]
Thank you for your quick response.
