### ISSUE TITLE
`org-ml-headline-set-node-property` unable to set property to nil

### ISSUE THREAD

**Issue by neeasade** [ndwarshuis/om.el#26]
context: I'm trying to remove the properties drawer from a node before I render it as a string. 

The issue I'm running into can be shown with the last example in the docs [here](https://github.com/ndwarshuis/org-ml/blob/d856ac6f0afed0299a47ed77830c676fd0fa9e55/docs/api-reference.md#org-ml-headline-set-node-property-key-value-headline). 

with the content:

``` text
* headline
:PROPERTIES:
:ID:       fake
:END:
```

The example code returns the whole content, instead of just the headline like in the example:

``` emacs-lisp
(->> (org-ml-parse-this-headline)
     (org-ml-headline-set-node-property "ID" nil)
     (org-ml-to-trimmed-string))
;; => "* headline\n:PROPERTIES:\n:ID:       fake\n:END:"
;; ! expected: "* headline"
```

EDIT: org version: `Org mode version 9.4 (release_9.4-174-gf6e41c @ /home/neeasade/.emacs.d/straight/build/org/)`
EDIT: org-ml version: d856ac6f0afed0299a47ed77830c676fd0fa9e55 

OT: Thank you so much for org-ml. It has given me the tools for shaping org the way I want, and helped me cross the gap to "complete" WRT my personal notes system.

**Comment by ndwarshuis** [comment]
fixed with c2600661f120bfd570042a8d7daa3682343fae04
