### ISSUE TITLE
How do you modify children of `org-data` type.

### ISSUE THREAD

**Issue by Luis-Henriquez-Perez** [ndwarshuis/om.el#28]
I have a node of the form:

```elisp
(org-data (:begin 1 :end 700) (section) (headline) (headline))
```
I want to change the number of headlines. Specfically I want to add my own headlines and make sure the headlines are in alphabetical order based on title. However, `org-ml-set-children` raises the error `(error "Child type restrictions not found for %s" type)` for `org-data`. I'd like to be able to modify the children of the `org-data` type and use `(setf (buffer-string) (org-ml-to-string modified-node))` to change the buffer.

Also I could not find a build function for the `org-data` type.

**Comment by ndwarshuis** [comment]
This should be easy to add/fix, although I remember having a reason for not adding a build function for `org-data` (it may have been a lame reason).

**Comment by Luis-Henriquez-Perez** [comment]
So as far as I see it, we need to do two things.

1) update the element restrictions to include the `org-data` type

I will admit I don't completely understand these things.

> Alist of element node type restrictions for element branch nodes.
The types in the cdr of each entry may be children of the type held at
the car.

According to the docs it seems that the `org-data` entry would be `(org-data)`
because `org-data` cannot be the child of any other node. Also, it seems that
`org-data` should be added to the CDR of every other node because `org-data` can
contain any of them.

Let me know if my logic is correct. I'm worried there's some edge case with an
object node.

Concretely, if what I said is true we should.

a) add `(org-data)` to `org-ml--element-restrictions`.

b) add `org-data` to the cdr of all elements in `org-ml--element-restrictions`
(except for `org-data`).

2) Add a build function for org-data.

**Comment by ndwarshuis** [comment]
It would actually be the reverse. `org-data` can only have `headline` and `section` nodes so the thing to add is `(org-data headline section)` which translates to "org-data can have headline and section node children". Then have `org-data` absent from the rest means "org-data can't be a child of any other nodes".
