### ISSUE TITLE
Feature request(?): Getting keyword values

### ISSUE THREAD

**Issue by pgroce** [ndwarshuis/om.el#32]
Consider the following toplevel section:

```
#+STYLE: <link rel="stylesheet" type="text/css" href="style.css">
#+STARTUP: indent
#+TITLE: This is the title of the file

Toplevel section text
```

This generates the following `org-element` tree (via `org-ml-parse-this-toplevel-section`):

```
(section
 (:begin 1 :end 148 :contents-begin 1 :contents-end 147 :post-blank 1 :post-affiliated 1 :parent nil)
 (keyword
  (:key "STYLE" :value "<link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\">" :begin 1 :end 67 :post-blank 0 :post-affiliated 1 :parent #0))
 (keyword
  (:key "STARTUP" :value "indent" :begin 67 :end 85 :post-blank 0 :post-affiliated 67 :parent #0))
 (keyword
  (:key "TITLE" :value "This is the title of the file" :begin 85 :end 125 :post-blank 1 :post-affiliated 85 :parent #0))
 (paragraph
  (:begin 125 :end 147 :contents-begin 125 :contents-end 147 :post-blank 0 :post-affiliated 125 :parent #0)
  #("Toplevel section text\n" 0 22
    (:parent #1))))
```

My goal is to get the value of the `TITLE` keyword. (I.e., "This is the title of the file") I don't see how I can get there directly with the `org-ml` API, other than filtering the `section` node's children for `keyword` objects with the appropriate key. 

Am I missing a more straightforward way to get key/value information from the child keywords of an element? If not, I think some kind of simple API for access to keywords would be useful.

**Comment by ndwarshuis** [comment]
Does this work (`->>` from `dash.el`)?

``` clojure
(->> (org-ml-parse-this-toplevel-section)
     (org-ml-match '((:key "TITLE")))
     (car)
     (org-ml-get-property :value))
```

I agree that getting keywords should be 'simple' but to my knowledge org doesn't prevent the mixing of keywords and non-keywords so getting a specific keyword is going to be a generic search for a 'node that matches X' (like the above).

**Comment by pgroce** [comment]
> Does this work?

Yes, that was more or less what I had settled on. I was also matching for the `keyword` type, which is probably unnecessary.

> to my knowledge org doesn't prevent the mixing of keywords and non-keywords so getting a specific keyword is going to be a generic search for a 'node that matches X' (like the above)

Agree, but I don't see how that's an argument against making access to keyword data more straightforward.

OTOH, it's also not a critical omission, and I think it's defensible to reject the suggestion on the basis that it's not core functionalty. `org-ml-match` provides an interface for general-purpose node selection, and keywords are nodes. A layer over keywords that abstracts them away from their status as nodes in the AST may not be appropriate to a library organized around providing functional access to the AST.

So I think I've talked myself out of this feature request. :)  Maybe instead there should be a "cookbook" section or something that shows how to use org-ml to accomplish various tasks like this one. Obviously one for the "future" pile, though.

**Comment by ndwarshuis** [comment]
I like the cookbook idea. In general, I don't want to add more functions that are simply the composition of a few other functions (like the above) since that would make the library combinatorially bigger, and it's easier for an end user to make them as they need them rather than me try to predict such a need. But I also understand that some compositions may not be obvious, hence the cookbook.
