### ISSUE TITLE
Cannot create headline

### ISSUE THREAD

**Issue by floscr** [ndwarshuis/om.el#5]
Both `build-headline` functions seem to be broken.

With either

```
(om-build-headline :title "really impressive title")
(om-build-headline! :title-text "really impressive title")
```

I get `om--arg-error: Argument type error: "Unsettable property ’:post-blank’ for type ’headline’ requested; settable properties are :archivedp, :commentedp, :footnote-section-p, :level, :pre-blank, :priority, :tags, :title, :todo-keyword, :raw-value, :todo-type"`

Emacs Version:
GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.10)

**Comment by ndwarshuis** [comment]
I can't reproduce this. Please paste the output of `(alist-get 'headline om--node-property-alist)`.

**Comment by floscr** [comment]
Ah, sorry, it now works, it might have been a caching issue of emacs, since this package is loaded differently from my other packages.

Thank you anyway for an outstanding package :bowing_man:

**Comment by floscr** [comment]
After some experimenting, I could not reproduce the error.
Might have been some caching issue from the package setup.
Sorry for the trouble.
